CONFIG_BOOT_SIGNATURE_TYPE_RSA=y
CONFIG_BOOT_SIGNATURE_KEY_FILE="/home/nam/zephyr-development/vendor/dinhnamuet/keys/dinhnamuet_key_rsa_2048.pem"
CONFIG_BOOT_VALIDATE_SLOT0=y
CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
CONFIG_BOOT_MAX_IMG_SECTORS_AUTO=n
CONFIG_BOOT_MAX_IMG_SECTORS=64
