CONFIG_LOG=y
CONFIG_WATCHDOG=y
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="/home/nam/zephyr-development/vendor/dinhnamuet/keys/dinhnamuet_key_rsa_2048.pem"
CONFIG_ADC=y
CONFIG_INPUT=y
CONFIG_JOYSTICK=y
CONFIG_ZBUS=y
CONFIG_HEAP_MEM_POOL_SIZE=2048
CONFIG_SENSOR=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_FLASH=y
CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_NVS=y
