CONFIG_LOG=y
CONFIG_WATCHDOG=y
CONFIG_IWDG_STM32_INITIAL_TIMEOUT=26000
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="/home/nam/zephyr-development/vendor/dinhnamuet/keys/dinhnamuet_key_rsa_2048.pem"
